import ProjectPageLayout from './ProjectPageLayout/ProjectPageLayout';
import ChapterHeader from './Section/ChapterHeader';
import PageSection from './Section/PageSection';
import StyledLink from '../StyledLink/StyledLink';
import List from './List/List';
import Gameplay from '../../assets/img/app-screenshots/tmt/gameplay.png';
import Automation from '../../assets/img/app-screenshots/tmt/automation.png';
import AutomationWarning from '../../assets/img/app-screenshots/tmt/automation-warning.png';
import MatchDashboard from '../../assets/img/app-screenshots/tmt/match-dashboard.png';

const TMTPage = () => {
	return (
		<ProjectPageLayout type='Web App' title='Tournament Management Tool'>
			<img src={Gameplay} />
			<ChapterHeader>Project Overview</ChapterHeader>
			<PageSection title='About The App'>
				<p>
					The Tournament Management Tool is an all-purpose Electron-based app to
					assist in the management and organization of Super Smash Bros. Melee
					tournaments. This tool enables tournament organizers to easily manage
					and customize stream overlays and graphics, manage tournament matches,
					and perform automated tasks.
				</p>
				<p>
					The primary tech stack of the user client comprises of React,
					Electron, Node.js, and TypeScript. Additional technologies used
					include Redux, Socket.io, and the{' '}
					<StyledLink
						href='https://react.fluentui.dev/?path=/docs/concepts-introduction--page'
						external
					>
						Fluent UI Design System
					</StyledLink>
					.
				</p>
				<p>
					This app has been used for the production of the tournament series{' '}
					<StyledLink
						href={'https://www.start.gg/tournament/full-house-2024/details'}
						external
					>
						Full House
					</StyledLink>{' '}
					and various online tournaments.
				</p>
			</PageSection>
			<PageSection title='Main Features'>
				<div className='font-medium'>Start.gg API</div>
				<List>
					<li>
						Supports linking{' '}
						<StyledLink href='https://www.start.gg/' external>
							Start.gg
						</StyledLink>{' '}
						tournaments through{' '}
						<StyledLink href='https://developer.start.gg/docs/intro/' external>
							their GraphQL API
						</StyledLink>{' '}
						to gain access to many quality of life features, including match
						selection and player selection.
					</li>
					<li>
						Call, report, and view matches entirely within the app interface.
					</li>
				</List>
				<div className='font-medium'>Stream Overlay Controls</div>
				<List>
					<li>
						The primary use of this app is to provide controls for a custom
						frontend stream overlay for the tournament.
					</li>
					<li>
						Easily update to relevant match information by selecting Start.gg
						matches.
					</li>
				</List>
				<div className='font-medium'>Slippi Automation and Statistics</div>
				<List>
					<li>
						This app makes use of the{' '}
						<StyledLink
							href='https://github.com/project-slippi/slippi-js'
							external
						>
							slippi-js
						</StyledLink>{' '}
						Project Slippi SDK to help compute stats and read live game data
						from replay files generated by live games.
					</li>
					<li>
						Using the{' '}
						<StyledLink href='https://github.com/vinceau/slp-realtime' external>
							slp-realtime
						</StyledLink>{' '}
						library, tasks such as updating character and port information,
						switching scenes, and updating game scores can be completely
						automated.
					</li>
				</List>
				<div className='font-medium'>Local Data</div>
				<List>
					<li>
						Save local player and commentator data to easily update character,
						team, and other stream interface data without having to manually set
						it for common players.
					</li>
				</List>
				<div className='font-medium'>OBS Websocket</div>
				<List>
					<li>
						Enables connecting to an OBS Studio client through OBS Websocket.
					</li>
					<li>
						Control and switch active scenes, and enable autoswitching through
						the stream management interface.
					</li>
				</List>
			</PageSection>
			<PageSection title='Planned Features'>
				<div className='font-medium'>Stream Widgets</div>
				<List>
					<li>
						Fully customizable and modular widgets for use in stream overlay,
						including in-game event alerts, marquees, slides, and more.
					</li>
				</List>
				<div className='font-medium'>Game/Combo Highlights</div>
				<List>
					<li>Automatically detect and queue game and combo highlights.</li>
				</List>
				<div className='font-medium'>Twitch Predictions</div>
				<List>
					<li>
						Connect with Twitch to provide on-stream Twitch prediction stream
						elements to increase view interaction.
					</li>
				</List>
			</PageSection>
			<PageSection title='App Preview'>
				<div className='mt-6 flex lg:flex-row flex-col gap-8'>
					<img
						src={Automation}
						alt='Automation Preview'
						className='max-w-lg w-full mx-auto mb-6'
					/>
					<img
						src={AutomationWarning}
						alt='Automation Warning Preview'
						className='max-w-lg w-full mx-auto mb-6'
					/>
				</div>
				<div className='mt-6 flex lg:flex-row flex-col gap-8'>
					<img
						src={MatchDashboard}
						alt='Match Dashboard Preview'
						className='max-w-lg w-full mx-auto mb-6'
					/>
				</div>
			</PageSection>
		</ProjectPageLayout>
	);
};

export default TMTPage;
